command /기본템:
    trigger:
        if {기본템::%uuid of player%} is set:
            send "&c이미 기본템을 받았음!" to player
            stop

        set {기본템::%uuid of player%} to true

        give iron sword to player
        give iron pickaxe to player
        give iron axe to player
        give iron shovel to player
        give 64 cooked beef to player

        send "&a기본 아이템 지급 완료!" to player